[results] Create initial peribolus config.
tektoncd/community pull request #289
Opened 2020-12-07 21:49 UTC by wlynch

Creates initial maintainer/collaborator team for new results project.

Primarily based on the existing OWNERS config
(https://github.com/tektoncd/results/blob/b113f90d53db800a9f6cb402fe6abc230f4ae55c/OWNERS).

For group maintainers, chose admins + wlynch.

Fixes #288

2020-12-07 22:14 UTC, wlynch commented
/cc @afrittoli

2020-12-08 09:20 UTC, vdemeester approved these changes

2020-12-08 11:45 UTC, afrittoli commented on org/org.yaml
> +          results read
Looks like there's a ":" missing

2020-12-08 11:46 UTC, afrittoli requested changes
I should add a peribolos dry-run CI job to validate the syntax :P

2020-12-08 14:39 UTC, wlynch commented on org/org.yaml
> +          results read
Whoops! Fixed.

2020-12-08 21:24 UTC, wlynch commented
/assign afrittoli

2020-12-14 17:14 UTC, afrittoli reviewed
Thanks for the updates!
/lgtm
/approve

2020-12-14 17:14 UTC, afrittoli approved these changes

2020-12-14 17:16 UTC, merged