TEP-0086: Larger Results via Sidecar Logs
tektoncd/community pull request #745
Opened 2022-06-28 16:03 UTC by jerop

In this change, we propose moving forward with Sidecar Logs as the
solution for providing larger Results within the CRDs.

/kind tep

2022-06-28 16:10 UTC, jerop commented
/assign @pritidesai

2022-06-28 16:12 UTC, wlynch commented
/cc @wlynch

2022-06-28 16:20 UTC, pritidesai commented
/assign

2022-06-28 16:22 UTC, jerop commented
@tlawrie @imjasonh @tomcli @ScrapCodes - thought this may be of interest to you, please take a look

2022-06-28 17:14 UTC, wlynch requested changes

2022-06-28 17:14 UTC, wlynch commented on teps/0086-changing-the-way-result-parameters-are-stored.md
>  ## Alternatives
Another alternative that might help with some of the sidecar issues mentioned above - OIDC API but using the entrypoint as the client instead of a dedicated sidecar.

- You can reuse the existing Pod resources to handle the uploading (no additional sidecar overhead).
- There's no ambiguity when the user container is complete.
- Avoids concerns about result availability since the upload is done from the user Pod itself.

2022-06-28 17:26 UTC, jerop commented on teps/0086-changing-the-way-result-parameters-are-stored.md
>  ## Alternatives
is it the same alternative described in https://github.com/tektoncd/community/blob/main/teps/0086-changing-the-way-result-parameters-are-stored.md#considerations? 

in that case, the OIDC approach involves storing the results externally (HTTP server) which is something we can explore alongside the solutions for external storage

cc @pritidesai

2022-06-28 17:28 UTC, jerop commented on teps/0086-changing-the-way-result-parameters-are-stored.md
> +controller will access the stdout logs of the `Sidecar`, extract the `Result` and its contents during reconciliation.
@chitrangpatel please look into whether this is possible in the POC

2022-06-28 17:29 UTC, chitrangpatel commented on teps/0086-changing-the-way-result-parameters-are-stored.md
> +controller will access the stdout logs of the `Sidecar`, extract the `Result` and its contents during reconciliation.
The controller needs to access the resource `pods/log` and requires `get` access. I don't think we can go finer than a pod (but I could be wrong). The sidecar runs in a different container in the the same pod as the other steps so in principle, the controller can access the logs of the other sidecars/steps in the same task. While accessing the logs, we need to provide the `pod` and the `container` name.

2022-06-28 17:34 UTC, wlynch commented on teps/0086-changing-the-way-result-parameters-are-stored.md
>  ## Alternatives
Similar, but without the Sidecar. You also don't need to store the results externally - the OIDC API can sit local on the cluster and write to the Results to the CRD similar to what's proposed with the log based approach. The OIDC bits are just to ensure that the upload requests are coming from the expected Pods.

2022-06-28 18:04 UTC, pritidesai commented on teps/0086-changing-the-way-result-parameters-are-stored.md
>  ## Alternatives
thanks @wlynch who will be responsible for managing OIDC? Do we need a separate controller to manage the API? How would the pipeline controller work without access to openID?

2022-06-28 18:14 UTC, pritidesai commented on teps/0086-changing-the-way-result-parameters-are-stored.md
> +- If a `Step` fails to produce a `Result`, the `Sidecar` will continue to look for the `Result` until it times out.
This is a very common case. We can impose the restriction mentioned in https://github.com/tektoncd/pipeline/issues/3497 but even with this restriction, we will have to find a way to fail instead of letting it time out.

2022-06-28 18:15 UTC, pritidesai commented on teps/0086-changing-the-way-result-parameters-are-stored.md
> +- No guarantees on when logs will be available - would have to wait for this before considering a `TaskRun` complete.
Please elaborate this caveat. How is this kind of wait designed or implemented?

2022-06-28 18:21 UTC, pritidesai commented on teps/0086-changing-the-way-result-parameters-are-stored.md
> +- The storage of the result parameter may still be limited by the [1.5 MB CRD size][crd-size].
I wouldn't document saying the results can be 1.5MB. Complex tasks with multiple steps (which is generally the case) might take away sufficient storage space. We can document the limitation saying the maximum allowed result size depends on the CRD, the max allowed CRD size - the actual CRD size. Also, this is split among all the results of a task.

How is the storage size distributed if my task has multiple results?

2022-06-28 18:33 UTC, chitrangpatel commented on teps/0086-changing-the-way-result-parameters-are-stored.md
> +- If a `Step` fails to produce a `Result`, the `Sidecar` will continue to look for the `Result` until it times out.
I think this was also my worry while I was thinking through the logic. In practice, when a step errors out, I think the controller kills all the sidecar and step containers and fails the task. I don't think timeout is a worry. I will update the text here. I will add some examples to demonstrate this.

2022-06-28 18:39 UTC, wlynch commented on teps/0086-changing-the-way-result-parameters-are-stored.md
> +controller will access the stdout logs of the `Sidecar`, extract the `Result` and its contents during reconciliation.
I'd like to push back on this. 😢

User logs can contain PII and other sensitive information, so granting the Tekton Pipeline controller global read access to all Pod logs in the cluster (incl. non-Tekton pods) by default seems overreaching. IIRC, there's also no good way today to scope this dynamically or to only resources you create without granting the controller global RBAC modify permissions. 😭

2022-06-28 18:39 UTC, wlynch commented on teps/0086-changing-the-way-result-parameters-are-stored.md
>  ## Alternatives
IIRC, the rough plan was to use the built in cluster [service account token projection](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection), then use the [TokenReview API](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-review-v1/) to verify the token (or worst case verify via [OIDC discovery](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-issuer-discovery)) to authz requests coming from Pods. I think it's reasonable to require this, especially since it's been stable since 1.20 and I think most cloud providers have this enabled by default.

Task output API would be hosted in a container controlled by Tekton itself, probably another Pod in the `tekton-pipelines` namespace so that it can have separate RBAC permissions from the controller.

cc @tlawrie @mattmoor in case I missed anything.

2022-06-28 18:40 UTC, chitrangpatel commented on teps/0086-changing-the-way-result-parameters-are-stored.md
> +file in the interim then only partial contents will be considered as `Results`.
The sidecar runs a script that periodically(every second) executes the following logic:

1. Look for new files (aka. result names) in the directory /tekton/results.
2. It keeps a tally of which result (a file in the above directory) it has already checked. This way, each result is only checked once.
3. When a new result is found, it prints it to stdout in a parsable fashion.
4. When all the expected results are looked at, it breaks out of the periodic loop and exits.

Because of this flow, if the sidecar happens to find a file with missing or partial contents, it will think it has already read the results and not re-read it the next time. 

There is a way to get around this by computing the hash of the file contents and ensuring that there is content in the files and when the contents stop changing after a few 1-s loops, we can assume that the results have been written completely. This might add a slight delay but should be safer.

2022-06-28 18:42 UTC, chitrangpatel commented on teps/0086-changing-the-way-result-parameters-are-stored.md
> +- The storage of the result parameter may still be limited by the [1.5 MB CRD size][crd-size].
I agree with your statement. There is no firm upper limit to the results. As long as the total CRD limit is not crossed, its fair game. If we have 100s of results, that we store in the CRD then they have to share the CRD limit.

2022-06-28 19:57 UTC, jerop commented on teps/0086-changing-the-way-result-parameters-are-stored.md
>  ## Alternatives
@wlynch thanks for sharing this alternative - it sounds worthwhile pursing and was wondering if you could add it to the alternatives listed in https://github.com/tektoncd/community/blob/main/teps/0086-changing-the-way-result-parameters-are-stored.md#alternatives 🙏🏾

2022-06-28 20:56 UTC, chitrangpatel commented on teps/0086-changing-the-way-result-parameters-are-stored.md
> +controller will access the stdout logs of the `Sidecar`, extract the `Result` and its contents during reconciliation.
I agree.

2022-06-28 21:50 UTC, jerop commented on teps/0086-changing-the-way-result-parameters-are-stored.md
> +- The storage of the result parameter may still be limited by the [1.5 MB CRD size][crd-size].
that makes it much clearer, updated this caveat

2022-06-28 21:51 UTC, jerop commented on teps/0086-changing-the-way-result-parameters-are-stored.md
> +- No guarantees on when logs will be available - would have to wait for this before considering a `TaskRun` complete.
removed this caveat and updated the workflow to reflect that we're not just looking at the new results - left out the implementation details - thanks @chitrangpatel and @pritidesai

2022-06-28 21:54 UTC, jerop commented on teps/0086-changing-the-way-result-parameters-are-stored.md
> +file in the interim then only partial contents will be considered as `Results`.
removed this caveat and updated the workflow to reflect that we're not just looking at the new results - left out the implementation details - thanks @chitrangpatel and @pritidesai

2022-06-29 06:10 UTC, tlawrie commented
Hi @jerop I think its fantastic that a PoC was achieved.

> we propose moving forward with Sidecar Logs as the solution for providing larger Results within the CRDs.
IMO, there are a number of concerns with the sidecar log tailing approach that I think would put pause on proposing this as the final solution, considering the alternatives listed in the TEP.

I suggest either waiting for the other PoC is finished, or alternatively continuing with a new PoC to determine if one of the other alternatives may be better suited to solving this challenge.

2022-06-29 12:30 UTC, jerop commented
> Hi @jerop I think its fantastic that a PoC was achieved.
> 
> > we propose moving forward with Sidecar Logs as the solution for providing larger Results within the CRDs.
> > IMO, there are a number of concerns with the sidecar log tailing approach that I think would put pause on proposing this as the final solution, considering the alternatives listed in the TEP.
> 
> I suggest either waiting for the other PoC is finished, or alternatively continuing with a new PoC to determine if one of the other alternatives may be better suited to solving this challenge.

@tlawrie didn't mean this as the only solution, intended this as a solution that we provide behind a feature flag so that we can experiment with it and find ways to address the concerns - and that we can do the same with the PoCs when they are ready - so that we can have tangible results to help us move this work forward, what do you think? can clarify the language to reflect this

2022-06-29 13:06 UTC, jerop commented on teps/0086-changing-the-way-result-parameters-are-stored.md
> +- If a `Step` fails to produce a `Result`, the `Sidecar` will continue to look for the `Result` until it times out.
cc @vinamra28

2022-06-29 15:17 UTC, jerop commented
> If we're not yet sure which solution we are going to land on as the primary answer long term, perhaps we should just leave this under alternatives?

@wlynch happy to move it to alternatives - what I care the most about is if we can make them implementable while gated behind feature flags so that we can experiment - what do you think?

2022-06-29 15:26 UTC, jerop commented
@wlynch @tlawrie @pritidesai @dibyom - moved the solution to the alternatives section and left the proposal to experiment behind feature gates - please take a look

2022-06-29 17:02 UTC, pritidesai commented on teps/0086-changing-the-way-result-parameters-are-stored.md
> +controller will access the stdout logs of the `Sidecar`, extract the `Result` and its contents during reconciliation.
I would like to understand this in a little more detail. Does the pipeline controller require `get` access to the `pod` which is created for executing the task which is producing the result or this is in general umbrella kind of access given to `get` logs from any pod in the cluster from any namespace?

2022-06-29 17:07 UTC, pritidesai commented on teps/0086-changing-the-way-result-parameters-are-stored.md
> +controller will access the stdout logs of the `Sidecar`, extract the `Result` and its contents during reconciliation.
Logs are anyways not the ideal place to store/echo any sensitive information specially if its a plaintext logs 🤣 but this best practice is often ignored 😄

2022-06-29 18:22 UTC, pritidesai commented on teps/0086-changing-the-way-result-parameters-are-stored.md
> +controller will access the stdout logs of the `Sidecar`, extract the `Result` and its contents during reconciliation.
I am not sure how granting this global permission can be implemented behind a feature flag? We can implement the feature flag in the controller to disallow reading of such logs but the cluster wide permissions might have already granted irrespective of the controller feature flag?

2022-06-29 18:28 UTC, jerop commented
> The other alternative is we just experiment in a fork until we have more confidence.

@wlynch it is hard to experiment and gather feedback from forks where visibility is limited. this is why we experimented with the alternatives for remote resolution (TEP-0086) behind feature flags to figure out a way forward - https://github.com/tektoncd/pipeline/pull/4168. the same kind experimentation approach i'm suggesting here. i believe this kind of experimentation to get tangible feedback from users and dogfooding is what will give us more confidence.

2022-06-29 18:35 UTC, chitrangpatel commented on teps/0086-changing-the-way-result-parameters-are-stored.md
> +controller will access the stdout logs of the `Sidecar`, extract the `Result` and its contents during reconciliation.
I see what you mean. This configuration is orthogonal to the feature flag. Let me investigate if we can update the RBAC permissions on the fly from the controller when we generate the sidecar.

2022-06-30 14:51 UTC, dibyom commented on teps/0086-changing-the-way-result-parameters-are-stored.md
> +controller will access the stdout logs of the `Sidecar`, extract the `Result` and its contents during reconciliation.
we probably don't want the controller or something in Tekton to have the permission to add RBAC configurations. One way might be that we can add a separate role just for this feature. To enable the feature, users have to bind this role to the controller's service account along with setting the feature flag.

Re: permission to logs - I agree global access is less than ideal but the controller already has read access to secrets across the cluster

2022-06-30 15:31 UTC, chitrangpatel commented on teps/0086-changing-the-way-result-parameters-are-stored.md
> +controller will access the stdout logs of the `Sidecar`, extract the `Result` and its contents during reconciliation.
@dibyom that's a much better way. Thanks!
I did not appreciate that the controller had access to the secrets. They probably contain more sensitive information that the logs.

2022-06-30 15:50 UTC, chitrangpatel commented on teps/0086-changing-the-way-result-parameters-are-stored.md
> +controller will access the stdout logs of the `Sidecar`, extract the `Result` and its contents during reconciliation.
I made this change in the [POC](https://github.com/chitrangpatel/pipeline/blob/POC-larger-results-sidecar-logs/config/200-clusterrole.yaml)

2022-06-30 16:05 UTC, imjasonh commented on teps/0086-changing-the-way-result-parameters-are-stored.md
> +controller will access the stdout logs of the `Sidecar`, extract the `Result` and its contents during reconciliation.
> Re: permission to logs - I agree global access is less than ideal but the controller already has read access to secrets across the cluster

I don't consider this a compelling reason to further expand our access to the cluster. We should work to reduce our permissions so that Tekton can be used in more environments, not use our existing overly-broad access to justify even more access going forward.

2022-06-30 21:14 UTC, dibyom commented
>  If we want to be more conservative, pretty sure we could also implement this with a mutating Pod admission webhook and just inject the sidecar / entrypoint without making changes to the Pipelines controller (though this won't work once SPIRE support lands). 🤷

I think we still need the controller changes for parsing the logs.

2022-06-30 21:25 UTC, dibyom commented
> @wlynch it is hard to experiment and gather feedback from forks where visibility is limited. this is why we experimented with the alternatives for remote resolution (TEP-0060) behind feature flags to figure out a way forward before we chose the solution - https://github.com/tektoncd/pipeline/pull/4168. the same experimentation approach i'm suggesting here. i believe this kind of experimentation to get tangible feedback from users and dogfooding/fishfooding is what will give us more confidence.

+1. I agree that while we have to be careful around not rearchitecting too much for an experiment, I think its worthwhile making it easy to try out the feature and gather feedback, and decide on the way forward.

In terms of marking the TEP implementable or not - personally I'm ok with experimenting without the implementable flag given that we haven't selected the way forward.

2022-07-26 14:16 UTC, chitrangpatel commented on teps/0086-changing-the-way-result-parameters-are-stored.md
> +- If a `Step` fails to produce a `Result`, the `Sidecar` will continue to look for the `Result` until it times out.
Correction.
If a step fails (ie. crashes), the sidecar will be killed by the controller.
However, if a step runs successfully, just does not write out the results, then the sidecar continues to run until it times out because its looking for the result. I will see if I can send out a kill signal to the sidecar if all the steps have successfully completed.

2022-07-26 15:18 UTC, chitrangpatel commented on teps/0086-changing-the-way-result-parameters-are-stored.md
> +- If a `Step` fails to produce a `Result`, the `Sidecar` will continue to look for the `Result` until it times out.
I will provide a suggestion for the text.

2022-07-26 15:21 UTC, chitrangpatel commented on teps/0086-changing-the-way-result-parameters-are-stored.md
> +- If a `Step` fails to produce a `Result`, the `Sidecar` will continue to look for the `Result` until it times out.
```suggestion
- If a `Step` fails to produce a `Result`, the `Sidecar` will continue to look for the `Result` until it times out.

If a `Step` fails to produce a `Result`, the `controller` will Stop the sidecar with the `nopImage` and error out.
```
I think we can omit the line entirely since it is no longer a caveat.
```suggestion
- If a `Step` fails to produce a `Result`, the `Sidecar` will continue to look for the `Result` until it times out.
```

2022-08-02 21:07 UTC, jerop commented
@dibyom @pritidesai @vdemeester please take a look

cc @wlynch @tlawrie @imjasonh @chitrangpatel

2022-08-03 23:26 UTC, dibyom reviewed
Thanks @jerop 

Have we done any measurements around the overhead of 1. adding a sidecar to each taskRun that requires a result and 2. having the reconciler parse potentially a few MBs worth of results in the controller itself

2022-08-03 23:26 UTC, dibyom commented on teps/0086-changing-the-way-result-parameters-are-stored.md
> +This provides an opportunity to experiment with this solution to provide `Results` within the CRDs as we figure out
+1  In general, I'd like us to decouple the storing results outside the CRD problem from the results can only be a few KB problem. I think being able to store results above a few KB will unlock quite a few use cases regardless of whether the result is stored in the CRD or not. And storing it in the CRD is a great first step since we don't have to figure out the interfaces for fetching results from external storage either.

That being said, we should also experiment with other ways of getting these larger results from the TaskRun onto the CRD e.g. sending results over HTTPS

2022-08-04 14:36 UTC, chitrangpatel commented
> Thanks @jerop
> 
> Have we done any measurements around the overhead of 1. adding a sidecar to each taskRun that requires a result and 2. having the reconciler parse potentially a few MBs worth of results in the controller itself

@dibyom I was supposed to do that but I completely missed it. When you say `overhead`, you just mean in terms of memory and CPU footprint of the pods right? If so, I can start gathering metrics right away.

2022-08-04 19:15 UTC, dibyom commented
> @dibyom I was supposed to do that but I completely missed it. When you say overhead, you just mean in terms of memory and CPU footprint of the pods right? If so, I can start gathering metrics right away.

No worries :) I think pod/run startup time would also be a good thing to measure

2022-08-05 17:08 UTC, chitrangpatel commented
> > @dibyom I was supposed to do that but I completely missed it. When you say overhead, you just mean in terms of memory and CPU footprint of the pods right? If so, I can start gathering metrics right away.
> 
> No worries :) I think pod/run startup time would also be a good thing to measure

@wlynch @dibyom @jerop I did the overhead tests. 
For the test, I spawned 20-30 pipeline runs, each with 3 tasks (each with two steps) and gathered metrics from the `metrics server` during the tests. I ran it with and without sidecar logs.
Here are the results:
```
CPU: 1% difference
Memory: 0.2% difference
Start time: 3 s difference per task (I think this is the most significant difference)
``` 
### overhead with sidecar logs
![overhead_with_sidecar_logs](https://user-images.githubusercontent.com/11685590/183126657-b208b369-cb55-4316-a023-b4914c90965b.png)

### overhead without sidecar logs
![overhead_without_sidecar_logs](https://user-images.githubusercontent.com/11685590/183126663-729963d1-021c-465a-b9cb-c801b7541966.png)

2022-08-08 16:15 UTC, afrittoli commented
/assign @afrittoli

2022-08-08 16:41 UTC, dibyom commented
@chitrangpatel Thank you so much for the performance benchmarking numbers. The extra 3s overhead to startup time per taskrun is a bit concerning. Wondering - does the latency go up if say you increase the load (e.g. run 50 pipelineruns concurrently).

From a mitigation standpoint, it might help if we only inject the sidecars if we know we the task is writing a result.

2022-08-08 19:40 UTC, chitrangpatel commented
> @chitrangpatel Thank you so much for the performance benchmarking numbers. The extra 3s overhead to startup time per taskrun is a bit concerning. Wondering - does the latency go up if say you increase the load (e.g. run 50 pipelineruns concurrently).
> 
Yes, I was very concerned about the 3 s overhead too. Its an increase by ~50% from the average ~6 s overhead without the results sidecar.
I can check. Although I will have to figure out a way to accurately measure start-up times instead of eye-balling the k9s screen 50 times (like I did last time 😄 )

> From a mitigation standpoint, it might help if we only inject the sidecars if we know we the task is writing a result.

Yes, this is already the case. The task run reconciler will check if the steps in the task are producing any results and only inject a results sidecar in that case.

2022-08-10 15:49 UTC, dibyom commented
> I can check the times when I increase the load. Although I will have to figure out a way to accurately measure start-up times instead of eye-balling the k9s screen 50 times (like I did last time 😄 )

Given that this is a prototype I think that's ok - we can use these numbers as a baseline to compare to

2022-08-29 16:18 UTC, pritidesai commented
API WG - on agenda for further discussion

2022-11-30 20:43 UTC, jerop commented
opened a new TEP instead of updating TEP-0086 - https://github.com/tektoncd/community/pull/887 - so closing this PR

2022-11-30 20:43 UTC, closed without merging